[package]

name = "rusty-chess"
version = "0.0.1"
authors = [ "Eugene Zemtsov <e.zemtsov@gmail.com>" ]

[[bin]]

name = "rchess"

[dependencies]
rand = "0.3.8"

[profile.test]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
